import { ClerkProvider } from '@clerk/nextjs';
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Inter } from "next/font/google";
import "./globals.css";
import { dark } from '@clerk/themes';

const inter=Inter({subsets:["latin"]});
export const metadata = {
  title: "AI Career Coach",
  description: "Generated by ",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}>
    <html
      lang="en"
      className={` ${inter.className}`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header />
           <main className="min-h-screen">{children}</main> 
           {/* footer */}
           <footer className="bg-muted/50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p>made by</p>
            </div>
           </footer>
          </ThemeProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
